import { User } from './types';

export const users: User[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    role: 'investor',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Seasoned investor in early-stage SaaS and fintech startups. Looking for disruptive ideas with strong founding teams.',
    investmentInterests: ['SaaS', 'Fintech', 'AI', 'HealthTech'],
    portfolioCompanies: [
      { name: 'Innovate Inc.', url: '#' },
      { name: 'FinTech Solutions', url: '#' },
    ],
  },
  {
    id: '2',
    name: 'Bob Smith',
    email: 'bob@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Founder of ConnectSphere, a social networking platform for professionals. Former software engineer at a FAANG company.',
    startupName: 'ConnectSphere',
    startupDescription: 'A revolutionary AI-powered platform designed to enhance professional networking by suggesting meaningful connections based on skills, experience, and career goals.',
    fundingNeeds: '$500,000 for 10% equity. Funds will be used for marketing and scaling our engineering team.',
    pitchDeckUrl: '#',
  },
  {
    id: '3',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    role: 'investor',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Venture capitalist with a focus on deep tech and renewable energy. Passionate about supporting technology that makes a positive impact on the world.',
    investmentInterests: ['Deep Tech', 'Renewable Energy', 'Sustainability'],
    portfolioCompanies: [
      { name: 'QuantumLeap', url: '#' },
      { name: 'Solaris', url: '#' },
    ],
  },
  {
    id: '4',
    name: 'Diana Prince',
    email: 'diana@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'CEO of Healthera, a digital health platform providing personalized wellness plans. Background in medicine and public health.',
    startupName: 'Healthera',
    startupDescription: 'A mobile-first platform that uses AI to create personalized fitness and nutrition plans, connecting users with certified coaches and a supportive community.',
    fundingNeeds: '$1.2M for clinical trials and market expansion.',
    pitchDeckUrl: '#',
  },
    {
    id: '5',
    name: 'Ethan Hunt',
    email: 'ethan@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Creator of EcoTrack, an app helping consumers make sustainable purchasing decisions.',
    startupName: 'EcoTrack',
    startupDescription: 'EcoTrack scans product barcodes to provide a comprehensive sustainability score, empowering consumers to make environmentally conscious choices.',
    fundingNeeds: '$300,000 for product development and user acquisition.',
    pitchDeckUrl: '#',
  },
   {
    id: '6',
    name: 'Fiona Glenanne',
    email: 'fiona@example.com',
    role: 'investor',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Angel investor specializing in consumer goods and e-commerce. Enjoys working with first-time founders.',
    investmentInterests: ['E-commerce', 'Consumer Goods', 'Marketplaces'],
    portfolioCompanies: [
      { name: 'ShopEasy', url: '#' },
      { name: 'DirectStyle', url: '#' },
    ],
  },
  {
    id: '7',
    name: 'George Lucas',
    email: 'george@example.com',
    role: 'investor',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Focused on scaling e-commerce and marketplace businesses. I bring operational expertise and a network of industry contacts.',
    investmentInterests: ['E-commerce', 'Marketplaces', 'Logistics', 'B2C'],
    portfolioCompanies: [
      { name: 'QuickShip', url: '#' },
      { name: 'MarketGrid', url: '#' }
    ],
  },
  {
    id: '8',
    name: 'Hannah Montana',
    email: 'hannah@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Building the future of remote work collaboration tools.',
    startupName: 'SyncUp',
    startupDescription: 'A real-time collaborative whiteboard and project management tool designed for distributed teams to brainstorm and execute ideas seamlessly.',
    fundingNeeds: '$750,000 to expand our feature set and integrate with other platforms.',
    pitchDeckUrl: '#',
  },
  {
    id: '9',
    name: 'Ivy Green',
    email: 'ivy@example.com',
    role: 'investor',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Ex-founder with a passion for funding the next generation of AI-driven B2B SaaS companies.',
    investmentInterests: ['AI', 'SaaS', 'B2B', 'Machine Learning'],
    portfolioCompanies: [
        { name: 'Cognitive AI', url: '#' },
        { name: 'SalesFlow', url: '#' }
    ],
  },
  {
    id: '10',
    name: 'Jack Sparrow',
    email: 'jack@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Disrupting the food tech industry with sustainable solutions.',
    startupName: 'FutureFoods',
    startupDescription: 'We create delicious, plant-based alternatives to meat products using a proprietary fermentation process. Our mission is to reduce the environmental impact of the food industry.',
    fundingNeeds: '$2M for a new production facility and retail distribution.',
    pitchDeckUrl: '#',
  }
];
