import { User } from './types';

export const users: User[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    role: 'investor',
    avatarUrl: 'https://i.pinimg.com/originals/7d/34/d9/7d34d95b13a393d3a4e979a326b0a2a4.jpg',
    bio: 'Seasoned investor in early-stage SaaS and fintech startups. Looking for disruptive ideas with strong founding teams.',
    investmentInterests: ['SaaS', 'Fintech', 'AI', 'HealthTech'],
    portfolioCompanies: [
      { name: 'Innovate Inc.', url: '#' },
      { name: 'FinTech Solutions', url: '#' },
    ],
    bookmarkedProfiles: [],
  },
  {
    id: '2',
    name: 'Bob Smith',
    email: 'bob@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://i.pinimg.com/originals/d0/5c/4a/d05c4a7e93093259645934b172a6b22c.jpg',
    bio: 'Founder of ConnectSphere, a social networking platform for professionals. Former software engineer at a FAANG company.',
    startupName: 'ConnectSphere',
    startupDescription: 'A revolutionary AI-powered platform designed to enhance professional networking by suggesting meaningful connections based on skills, experience, and career goals.',
    fundingNeeds: '$500,000 for 10% equity. Funds will be used for marketing and scaling our engineering team.',
    pitchDeckUrl: '#',
    bookmarkedProfiles: [],
  },
  {
    id: '3',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    role: 'investor',
    avatarUrl: 'https://i.pinimg.com/originals/b7/a1/38/b7a138031d22fd16af455a7200ac7875.jpg',
    bio: 'Venture capitalist with a focus on deep tech and renewable energy. Passionate about supporting technology that makes a positive impact on the world.',
    investmentInterests: ['Deep Tech', 'Renewable Energy', 'Sustainability'],
    portfolioCompanies: [
      { name: 'QuantumLeap', url: '#' },
      { name: 'Solaris', url: '#' },
    ],
    bookmarkedProfiles: [],
  },
  {
    id: '4',
    name: 'Diana Prince',
    email: 'diana@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://i.pinimg.com/originals/4e/4a/4a/4e4a4a520a84e271a2575dd2b2a8d6b4.jpg',
    bio: 'CEO of Healthera, a digital health platform providing personalized wellness plans. Background in medicine and public health.',
    startupName: 'Healthera',
    startupDescription: 'A mobile-first platform that uses AI to create personalized fitness and nutrition plans, connecting users with certified coaches and a supportive community.',
    fundingNeeds: '$1.2M for clinical trials and market expansion.',
    pitchDeckUrl: '#',
    bookmarkedProfiles: [],
  },
    {
    id: '5',
    name: 'Ethan Hunt',
    email: 'ethan@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://i.pinimg.com/originals/8a/5e/28/8a5e28a5a4d3f5451a5119420b986b24.jpg',
    bio: 'Creator of EcoTrack, an app helping consumers make sustainable purchasing decisions.',
    startupName: 'EcoTrack',
    startupDescription: 'EcoTrack scans product barcodes to provide a comprehensive sustainability score, empowering consumers to make environmentally conscious choices.',
    fundingNeeds: '$300,000 for product development and user acquisition.',
    pitchDeckUrl: '#',
    bookmarkedProfiles: [],
  },
   {
    id: '6',
    name: 'Fiona Glenanne',
    email: 'fiona@example.com',
    role: 'investor',
    avatarUrl: 'https://i.pinimg.com/originals/a9/3f/76/a93f769f47cf97d6a5982d56a3103c83.jpg',
    bio: 'Angel investor specializing in consumer goods and e-commerce. Enjoys working with first-time founders.',
    investmentInterests: ['E-commerce', 'Consumer Goods', 'Marketplaces'],
    portfolioCompanies: [
      { name: 'ShopEasy', url: '#' },
      { name: 'DirectStyle', url: '#' },
    ],
    bookmarkedProfiles: [],
  },
  {
    id: '7',
    name: 'George Lucas',
    email: 'george@example.com',
    role: 'investor',
    avatarUrl: 'https://i.pinimg.com/originals/c8/1c/7d/c81c7d2427a14a38e078f4b8893d9a5c.jpg',
    bio: 'Focused on scaling e-commerce and marketplace businesses. I bring operational expertise and a network of industry contacts.',
    investmentInterests: ['E-commerce', 'Marketplaces', 'Logistics', 'B2C'],
    portfolioCompanies: [
      { name: 'QuickShip', url: '#' },
      { name: 'MarketGrid', url: '#' }
    ],
    bookmarkedProfiles: [],
  },
  {
    id: '8',
    name: 'Hannah Montana',
    email: 'hannah@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://i.pinimg.com/originals/5c/9a/c3/5c9ac3076a5a041416e881c1c1f1f1d1.jpg',
    bio: 'Building the future of remote work collaboration tools.',
    startupName: 'SyncUp',
    startupDescription: 'A real-time collaborative whiteboard and project management tool designed for distributed teams to brainstorm and execute ideas seamlessly.',
    fundingNeeds: '$750,000 to expand our feature set and integrate with other platforms.',
    pitchDeckUrl: '#',
    bookmarkedProfiles: [],
  },
  {
    id: '9',
    name: 'Ivy Green',
    email: 'ivy@example.com',
    role: 'investor',
    avatarUrl: 'https://i.pinimg.com/originals/de/64/2d/de642dadd1c55d73c723f53bb16790b9.jpg',
    bio: 'Ex-founder with a passion for funding the next generation of AI-driven B2B SaaS companies.',
    investmentInterests: ['AI', 'SaaS', 'B2B', 'Machine Learning'],
    portfolioCompanies: [
        { name: 'Cognitive AI', url: '#' },
        { name: 'SalesFlow', url: '#' }
    ],
    bookmarkedProfiles: [],
  },
  {
    id: '10',
    name: 'Jack Sparrow',
    email: 'jack@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://i.pinimg.com/originals/7b/07/77/7b077794356a81e35f5c3866b7a2c4e7.jpg',
    bio: 'Disrupting the food tech industry with sustainable solutions.',
    startupName: 'FutureFoods',
    startupDescription: 'We create delicious, plant-based alternatives to meat products using a proprietary fermentation process. Our mission is to reduce the environmental impact of the food industry.',
    fundingNeeds: '$2M for a new production facility and retail distribution.',
    pitchDeckUrl: '#',
    bookmarkedProfiles: [],
  }
];
