import { User } from './types';

export const users: User[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    role: 'investor',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Seasoned investor in early-stage SaaS and fintech startups. Looking for disruptive ideas with strong founding teams.',
    investmentInterests: ['SaaS', 'Fintech', 'AI', 'HealthTech'],
    portfolioCompanies: [
      { name: 'Innovate Inc.', url: '#' },
      { name: 'FinTech Solutions', url: '#' },
    ],
  },
  {
    id: '2',
    name: 'Bob Smith',
    email: 'bob@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Founder of ConnectSphere, a social networking platform for professionals. Former software engineer at a FAANG company.',
    startupName: 'ConnectSphere',
    startupDescription: 'A revolutionary AI-powered platform designed to enhance professional networking by suggesting meaningful connections based on skills, experience, and career goals.',
    fundingNeeds: '$500,000 for 10% equity. Funds will be used for marketing and scaling our engineering team.',
    pitchDeckUrl: '#',
  },
  {
    id: '3',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    role: 'investor',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Venture capitalist with a focus on deep tech and renewable energy. Passionate about supporting technology that makes a positive impact on the world.',
    investmentInterests: ['Deep Tech', 'Renewable Energy', 'Sustainability'],
    portfolioCompanies: [
      { name: 'QuantumLeap', url: '#' },
      { name: 'Solaris', url: '#' },
    ],
  },
  {
    id: '4',
    name: 'Diana Prince',
    email: 'diana@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'CEO of Healthera, a digital health platform providing personalized wellness plans. Background in medicine and public health.',
    startupName: 'Healthera',
    startupDescription: 'A mobile-first platform that uses AI to create personalized fitness and nutrition plans, connecting users with certified coaches and a supportive community.',
    fundingNeeds: '$1.2M for clinical trials and market expansion.',
    pitchDeckUrl: '#',
  },
    {
    id: '5',
    name: 'Ethan Hunt',
    email: 'ethan@example.com',
    role: 'entrepreneur',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Creator of EcoTrack, an app helping consumers make sustainable purchasing decisions.',
    startupName: 'EcoTrack',
    startupDescription: 'EcoTrack scans product barcodes to provide a comprehensive sustainability score, empowering consumers to make environmentally conscious choices.',
    fundingNeeds: '$300,000 for product development and user acquisition.',
    pitchDeckUrl: '#',
  },
   {
    id: '6',
    name: 'Fiona Glenanne',
    email: 'fiona@example.com',
    role: 'investor',
    avatarUrl: 'https://placehold.co/100x100.png',
    bio: 'Angel investor specializing in consumer goods and e-commerce. Enjoys working with first-time founders.',
    investmentInterests: ['E-commerce', 'Consumer Goods', 'Marketplaces'],
    portfolioCompanies: [
      { name: 'ShopEasy', url: '#' },
      { name: 'DirectStyle', url: '#' },
    ],
  },
];
